First Pull request
che30/YoutubeCloneCR1230 pull request #1
Opened 2020-09-18 22:12 UTC by mke2111

2020-09-18 22:21 UTC, acushlakoncept requested changes
## Hello @mke2111 and @che30 

### First of all, congrats in working on your first Microverse project 🌟

Add a more descriptive pull request mentioning what you were able to do in this project [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). The title should reflect the feature you added.

This Code Review Request will be marked as invalid on your Dashboard, so please submit a new one once you are ready!

Happy coding!
By Uduak Essien
Slack @acushla

2020-09-19 01:42 UTC, krys2fa requested changes
## Nice work team 👏 
Your project displays good use of semantic HTML as well as CSS classes. 💪 
You have a professional looking README file as well. 👍 

Just a few more adjustments to complete the project. They can be seen in the comments below:
### Status: Changes Required ♻️ 

Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2020-09-19 01:42 UTC, krys2fa commented on .vscode/settings.json
> +}
- [ ] [OPTIONAL] Files not related to the project should not be added to your commits. 
You can include this folder in the .gitignore in the future.

2020-09-19 01:42 UTC, krys2fa commented on index.html
> +                                    <div style="padding-right: 15px;"><i class="fas fa-ellipsis-h"></i></div>
- [ ] [REQUIRED] Inline styles should not be used as they fall under [basic bad CSS practices](https://speckyboy.com/good-bad-css-practices/) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright).
Please remove all inline styles from this file.

2020-09-19 01:42 UTC, krys2fa commented on index.html
> +        <div class="videos">
- [ ] [OPTIONAL] You are encouraged to use the `<main>` tag for the dominant content of the `<body>` of the document.

2020-09-19 06:01 UTC, mke2111 commented on index.html
> +                                    <div style="padding-right: 15px;"><i class="fas fa-ellipsis-h"></i></div>
Thanks for the review.
Changes have been made as suggested.

2020-09-19 08:33 UTC, teekaytech requested changes
# Status: Changes required :recycle: :vertical_traffic_light: 

## Hi team :wave: 

### You've done an awesome job so far :ok_hand:. But there are still some changes that are necessary for this project to be approved. 

**Let us quickly make some finishing touches and request another review.** 

Kindly review my points below :point_down: 

- Your `SUBSCRIBE` button is a screenshot. You're required to build your button with the appropriate HTML elements, and not a screenshot.
![1](https://user-images.githubusercontent.com/26856491/93662689-f94fa080-fa59-11ea-9bac-a80012af7da6.png)

![b](https://user-images.githubusercontent.com/26856491/93662690-0076ae80-fa5a-11ea-9fa4-f291f6cc0689.png)

- There's too much horizontal space in-between the `video section` column and the `recommended videos section` column. Kindly see the difference from the image below and make changes as necessary.

Your page:

![y](https://user-images.githubusercontent.com/26856491/93662745-4764a400-fa5a-11ea-8e92-5a0bb93d5887.png)

Actual page: 

![a](https://user-images.githubusercontent.com/26856491/93662766-6e22da80-fa5a-11ea-8af9-ed17ededf084.png)

* * *
**You can reach me on slack (@taofeekolalere)
Happy coding :bowing_man:**

2020-09-19 08:33 UTC, teekaytech commented on style.css
> +}
Kindly indent your CSS rules block.

2020-09-19 08:33 UTC, teekaytech commented on style.css
> +    }
Use proper indentation for these blocks.

2020-09-19 10:02 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-19 10:11 UTC, umairarshadbutt approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://che30.github.io/YoutubeCloneCR1230/) shows a good understanding and usage of embedding images and videos. :100:
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @che30  and @mke2111! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-19 10:19 UTC, merged